{
 "title": "Scheduler_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ongoing requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scheduler_ongoing_request_count)"
    }
   ]
  },
  {
   "title": "Ongoing requests",
   "type": "graph",
   "description": "Requests which are ongoing right now",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_ongoing_request_count",
     "legendFormat": "{{instance}} - {{endpoint}} - {{method}}"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "graph",
   "description": "Total request count since the application is up",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_request_count",
     "legendFormat": "{{instance}} - {{endpoint}} - {{method}} - response {{http_status}}"
    }
   ]
  },
  {
   "title": "Process open fds",
   "type": "singlestat",
   "description": "from Posix",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "Part of requests served in 5s during the last 1h",
   "type": "singlestat",
   "description": "Apdex score to track your SLA",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "  sum(rate(scheduler_request_response_time_seconds_bucket{le=\"5.0\"}[1h]))/sum(rate(scheduler_request_response_time_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "Process resident memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Average request response time during the last 5 min",
   "type": "graph",
   "description": "To track the response time of the application",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "response time, s" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_request_response_time_seconds_sum[5m])/rate(scheduler_request_response_time_seconds_count[5m])",
     "legendFormat": "{{instance}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests within given response time",
   "type": "graph",
   "description": "Total requests finished within given time since the application is up",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_request_response_time_seconds_bucket",
     "legendFormat": "{{endpoint}} - {{le}}s"
    }
   ]
  }
 ]
}