name: CD - Push docker images to dockerhub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # check if flask boots fine
      - name: Run flask container (scheduler)
        run: |
          docker-compose up -d scheduler

      - name: Print flask status
        run: |
          docker ps --filter "name=scheduler"

      - name: Fail if flask container is not running
        run: |
          if [[ x`docker ps --filter "name=scheduler" | grep Up` = x ]]; then exit 1; fi

      # run test suite
      - name: Print test results
        run: |
          docker exec scheduler pytest -v

      - name: Fail if tests are not 100%
        run: |
          if [[ x`docker exec scheduler pytest -v` =~ "FAILED" ]]; then exit 1; fi

      # push backend image to dockerhub
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Tag image with backend tag
        run: |
          docker image tag scheduler/scheduler ${{ secrets.DOCKER_USER }}/scheduler:scheduler

      - name: List images
        run: |
          docker image ls

      - name: Docker push
        run: |
          docker image push ${{ secrets.DOCKER_USER }}/scheduler:scheduler

      - name: Docker logout
        run: |
          docker logout

